apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: events-internal
  name: events-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-internal
  strategy: {}
  template:
    metadata:
      labels:
        app: events-internal
    spec:
      containers:
      - image: drehnstrom/events-internal:v1.0
        name: events-internal
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}